[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  publish = "dist"
  command = "pnpm run build && pnpm convex deploy"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200